name: Android Feature Branch CI

on:
  pull_request:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  basic_compile_and_test:
    name: Conduct basic apk compile and unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Compile apk
        run: ./gradlew :sample:assembleDebug
      - name: Run java unit tests
        run: ./gradlew :sample:testDebug